### ISSUE TITLE
SaveFile check output formats

### ISSUE THREAD

**Issue by ShockwaveNN** [ONLYOFFICE/doc-builder-testing#134]
SaveFile support a lot of output formats
https://api.onlyoffice.com/docbuilder/integrationapi/cdocbuilder/savefile

Need to add test which cheack every combination of input format (`builder.CreateFile`) and output format.
Also check incorrect combinations (like save `docx` to `csv`)

**Comment by flaminestone** [comment]
Fix: https://github.com/ONLYOFFICE/doc-builder-testing/pull/152
