### ISSUE TITLE
Check the new features of the builder in develop

### ISSUE THREAD

**Issue by trofim24** [ONLYOFFICE/doc-builder-testing#159]
- [x] - add function in Api GetSheets. Returns a Sheets collection that represents all the sheets in the active workbook.
- [x] - add getter property Sheets in Api
- [x] - add function in Api GetSheet. Returns an object that represents the sheet. Argument {string | number} nameOrIndex Sheet name or Sheet index.
- [x] - add functions in ApiWorksheet GetVisible, SetVisible, GetIndex
- [x] - add getter and setter properties Visible in ApiWorksheet
- [x] - add getter property Index in ApiWorksheet
- [x] - add getter and setter properties Name in ApiWorksheet
- [x] - add function in ApiWorksheet GetName

**Comment by trofim24** [comment]
- [ ] - add getter property ActiveCell in ApiWorksheet

**Comment by trofim24** [comment]
- [ ] - add function GetValue in ApiRange
- [ ] - add getter property Value in ApiRange

**Comment by trofim24** [comment]
- [ ] - add function Format in Api (https://msdn.microsoft.com/en-us/vba/language-reference-vba/articles/format-function-visual-basic-for-applications?f=255&MSPPError=-2147217396)

**Comment by trofim24** [comment]
- [ ] - add function ForEach in ApiRange

**Comment by trofim24** [comment]
- [ ] - add function GetCells in ApiApiWorksheet
- [ ] - add getter property Cells in ApiApiWorksheet

**Comment by trofim24** [comment]
- [ ] - add function GetUsedRange in ApiWorksheet
- [ ] - add getter property UsedRange in ApiWorksheet

**Comment by flaminestone** [comment]
https://github.com/ONLYOFFICE/doc-builder-testing/commit/bf8e66be2b53b744aa602b019db30a6d39b9821a
