### ISSUE TITLE
Check the new features in ApiRange and ApiWorksheet

### ISSUE THREAD

**Issue by AlexeyMatveev686** [ONLYOFFICE/doc-builder-testing#172]
- [x] add properties: MergeArea, WrapText in ApiRange
- [x] add property LeftMargin, RightMargin, TopMargin, BottomMargin, Orientation, PrintHeadings, PrintGridlines, Selection in ApiWorksheet
- [x] add functions: GetWrapText, SetWrapText, SetOffset, GetAddress in ApiRange
- [x] add functions:  SetLeftMargin, SetRightMargin, SetTopMargin, SetBottomMargin, GetLeftMargin, GetRightMargin, GetTopMargin, GetBottomMargin, SetPageOrientation, GetPageOrientation, GetSelection in ApiWorksheet

**Comment by flaminestone** [comment]
https://github.com/ONLYOFFICE/doc-builder-testing/commit/bf8e66be2b53b744aa602b019db30a6d39b9821a
